# Generated by Django 4.0 on 2022-01-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
                ('aadhar', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(blank=True, choices=[('b+ve', 'B Positive'), ('b-ve', 'B Negative'), ('o+ve', 'O Positive'), ('o-ve', 'O Negative'), ('a+ve', 'A Positive'), ('a-ve', 'A Negative'), ('ab+ve', 'AB Positive'), ('ab-ve', 'AB Negative')], max_length=10, null=True)),
                ('last_delivery_date', models.DateField(blank=True, null=True)),
                ('mode_of_delivery', models.CharField(blank=True, choices=[('normal', 'Normal'), ('cesarean', 'Cesarean'), ('forceps', 'Forceps'), ('vacuum', 'Vacuum'), ('other', 'Other')], max_length=10, null=True)),
                ('place_of_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(help_text='Any other remarks/complications')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother', to='vaccination.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('b+ve', 'B Positive'), ('b-ve', 'B Negative'), ('o+ve', 'O Positive'), ('o-ve', 'O Negative'), ('a+ve', 'A Positive'), ('a-ve', 'A Negative'), ('ab+ve', 'AB Positive'), ('ab-ve', 'AB Negative')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(help_text='Any other remarks/complications')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='vaccination.mother')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='vaccination.parent')),
            ],
        ),
    ]
