# Generated by Django 4.0 on 2022-01-08 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('b+ve', 'B Positive'), ('b-ve', 'B Negative'), ('o+ve', 'O Positive'), ('o-ve', 'O Negative'), ('a+ve', 'A Positive'), ('a-ve', 'A Negative'), ('ab+ve', 'AB Positive'), ('ab-ve', 'AB Negative')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Any other remarks/complications', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(blank=True, choices=[('b+ve', 'B Positive'), ('b-ve', 'B Negative'), ('o+ve', 'O Positive'), ('o-ve', 'O Negative'), ('a+ve', 'A Positive'), ('a-ve', 'A Negative'), ('ab+ve', 'AB Positive'), ('ab-ve', 'AB Negative')], max_length=10, null=True)),
                ('last_delivery_date', models.DateField(blank=True, null=True)),
                ('mode_of_delivery', models.CharField(blank=True, choices=[('normal', 'Normal'), ('cesarean', 'Cesarean'), ('forceps', 'Forceps'), ('vacuum', 'Vacuum'), ('other', 'Other')], max_length=10, null=True)),
                ('place_of_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Any other remarks/complications', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
                ('aadhar', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('designated_age', models.CharField(help_text='Designated age for this vaccine in weeks', max_length=100)),
                ('for_child', models.BooleanField(default=False)),
                ('for_mother', models.BooleanField(default=False)),
                ('extra_info', models.TextField(blank=True, help_text='Any other remarks/complications', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotherVaccinated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('extra_info', models.TextField(blank=True, help_text='Any other remarks/complications', null=True)),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_vaccinated', to='vaccination.mother')),
                ('vaccinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_vaccinated', to='auth.user')),
                ('vaccine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_vaccinated', to='vaccination.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='mother',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother', to='vaccination.parent'),
        ),
        migrations.CreateModel(
            name='ChildVaccinated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('extra_info', models.TextField(blank=True, help_text='Any other remarks/complications', null=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_vaccinated', to='vaccination.child')),
                ('vaccinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_vaccinated', to='auth.user')),
                ('vaccine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_vaccinated', to='vaccination.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='vaccination.mother'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='vaccination.parent'),
        ),
    ]
