# Generated by Django 4.0 on 2022-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
                ('aadhar', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
    ]
