# Generated by Django 4.0 on 2022-01-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0004_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('designated_age', models.CharField(help_text='Designated age for this vaccine in weeks', max_length=100)),
                ('for_child', models.BooleanField(default=False)),
                ('for_mother', models.BooleanField(default=False)),
                ('extra_info', models.TextField(blank=True, help_text='Any other remarks/complications', null=True)),
            ],
        ),
    ]
