# Generated by Django 4.0 on 2022-01-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vaccination', '0005_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildVaccinated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('extra_info', models.TextField(blank=True, help_text='Any other remarks/complications', null=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_vaccinated', to='vaccination.child')),
                ('vaccinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_vaccinated', to='auth.user')),
                ('vaccine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_vaccinated', to='vaccination.vaccine')),
            ],
        ),
    ]
